model_type: "bow_net"
num_labels: 3
vocab_size: 240465
vocab_path: "./data/vocab.txt"
data_dir: "./data"
inference_model_dir: "./inference_model"
save_checkpoint_dir: ""
init_checkpoint: ""
checkpoints: "./checkpoints/"
lr: 0.02
epoch: 10
batch_size: 24
do_train: True
do_val: True
do_infer: False
do_save_inference_model: False
max_seq_len: 20
skip_steps: 10
save_freq: 1
eval_freq: 1
random_seed: 0
output_dir: "./output"
use_cuda: True
